name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: sudo apt-get update
    - run: sudo apt-get install -y pulseaudio libportaudio2 dbus-x11 libasound-dev
    - name: Set up sound
      run: .github/scripts/setup_audio.sh
    - name: Build with Maven
      run: mvn package --file pom.xml
      shell: bash -e {0}
